name: pickles_rapyd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-383.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.3.0
  get: ^4.6.5
  camera: 0.10.0+4
  convex_bottom_bar: 3.1.0+1
  image_picker: 0.8.6
  qr_mobile_vision: 4.0.1
  mobile_scanner: 2.0.0
  flutter_barcode_scanner: 2.0.0
  ai_barcode: 3.2.4
  google_mlkit_text_recognition: 0.5.0
  cloud_firestore: 4.1.0
  image_cropper: 3.0.1
  google_ml_kit: 0.13.0
  firebase_auth: 4.1.4
  google_maps_flutter: 2.2.1
  flutter_polyline_points: 1.0.0
  carousel_slider: 4.1.1
  auto_size_text: 3.0.0
  map_launcher: 2.4.0
  flutter_svg: 1.1.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

