// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO35lWt4hLx4oTFE3IWUHjYDwExTv6DZk',
    appId: '1:97939368238:web:fe92f208bcd1cbbed8b2bf',
    messagingSenderId: '97939368238',
    projectId: 'pickles-9090e',
    authDomain: 'pickles-9090e.firebaseapp.com',
    storageBucket: 'pickles-9090e.appspot.com',
    measurementId: 'G-3HEP9EB2BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjkRddovVl_0U3d7Bm3JRq24mwEn3NXN0',
    appId: '1:97939368238:android:b09dd21493f53243d8b2bf',
    messagingSenderId: '97939368238',
    projectId: 'pickles-9090e',
    storageBucket: 'pickles-9090e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1yah5Z4IgEKp33zWjSi-5Y6yytG3ojc',
    appId: '1:97939368238:ios:7f9e0dd8069b843cd8b2bf',
    messagingSenderId: '97939368238',
    projectId: 'pickles-9090e',
    storageBucket: 'pickles-9090e.appspot.com',
    iosClientId: '97939368238-5htfgais78fkcobv1os6ridq2556ji5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.picklesRapyd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1yah5Z4IgEKp33zWjSi-5Y6yytG3ojc',
    appId: '1:97939368238:ios:7f9e0dd8069b843cd8b2bf',
    messagingSenderId: '97939368238',
    projectId: 'pickles-9090e',
    storageBucket: 'pickles-9090e.appspot.com',
    iosClientId: '97939368238-5htfgais78fkcobv1os6ridq2556ji5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.picklesRapyd',
  );
}
